# Generated by Django 6.0.2 on 2026-02-13 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('employment_status', models.CharField(blank=True, choices=[('student', 'Student'), ('intern', 'Intern'), ('employed_full', 'Employed Full-Time'), ('employed_part', 'Employed Part-Time'), ('freelance', 'Freelancer / Self-Employed'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('financial_goal', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
